# Generated by Django 4.2 on 2023-05-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userprofile',
        ),
    ]
