# Generated by Django 4.2 on 2023-05-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='verificat',
        ),
    ]
